// Nebula Shield — CPI Helpers
//
// Typed helpers for external programs (e.g. the AMM) to call Nebula Shield.
// Import this module when you have nebula-shield as a dependency with the
// `cpi` feature enabled in your Cargo.toml:
//
//   nebula-shield = { path = "...", features = ["cpi"] }
//
// Then call via:
//   nebula_shield::cpi::check_jit_protection(cpi_ctx, swap_amount, min_amount_out)?;
//
// The `cpi` feature is auto-generated by Anchor's #[program] macro.
// This module provides supporting types and documentation only.

use anchor_lang::prelude::*;

/// Shield status snapshot — emitted by get_shield_status instruction.
/// External callers can parse this from transaction logs or use the event.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub struct ShieldStatus {
    pub pool: Pubkey,
    pub enabled: bool,
    pub min_spread_bps: u16,
    pub cooldown_slots: u64,
    pub last_sweep_slot: u64,
    pub total_profit_a: u64,
    pub total_profit_b: u64,
    pub pools_protected: u64,
    pub total_jit_blocks: u64,
    pub total_arb_sweeps: u64,
}

/// Return data layout from check_jit_protection:
///   [0] = 0 → JIT blocked (JitBackRunDetected error also returned)
///   [0] = 1 → swap/removal is allowed
///
/// Return data from get_shield_status:
///   [0] = shield.enabled as u8
pub const CHECK_JIT_RETURN_BLOCKED: u8 = 0;
pub const CHECK_JIT_RETURN_ALLOWED: u8 = 1;
